name: Docs Deploy

on:
  push:
    branches:
      - master

jobs:
  push-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '18.x'

      # - name: Get Yarn Cache
      #   id: yarn-cache
      #   run: |
      #     corepack enable
      #     corepack prepare yarn@3.2.3 --activate
      #     echo "::set-output name=dir::$(yarn cache dir)"

      # - name: Cache Dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ steps.yarn-cache.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      - name: Set SSH Environment
        env:
          DOCS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTIONS_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com > ~/.ssh/known_hosts
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
          git config --local user.email "kimeunhye1201@gmail.com"
          git config --local user.name "Wunhae Kim 김은혜"

      - name: Build
        run: |
          npm install
          npm run build:github

      - name: Docs Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          publish_branch: gh-pages
          publish_dir: ./.vitepress/dist
          force_orphan: true
